[package]
name = "internal-service-map"
version = "0.1.0"
description = "Internal Service Map"
authors = ["Internal"]
edition = "2021"

[lib]
name = "internal_service_map_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
